### ISSUE TITLE
Comparison with XPlot wrapper

### ISSUE THREAD

**Issue by tpetricek** [plotly/Plotly.NET#1]
I just came across this library thanks to Sergey's F# weekly - it's great to see more work happening on a nice lightweight wrapper for Plotly! With the stand-alone open source release, Plotly seems to be the way to go for HTML charting these days.

Given that there is also the [XPlot Plotly wrapper](https://github.com/TahaHachana/XPlot/tree/master/src/XPlot.Plotly), so I was curious what are the main differences between the two? (Are the APIs very different? Are there some things that XPlot does not handle well?)

**Comment by muehlhaus** [comment]
Hi Tomas,
thanks for stopping by… I agree the library Plotly.js is a great way to go for HTML charting and XPlot Plotly provides a very good lightweighted wrapper. In FSharp.Plotly the major focus was to provide a look-and-feel as I was used to it from the awesome FSharp.Charting library. The main challenge to overcome was to provide a ‘Chart.combine’ that allows styling of the combined chart without destroying (but possible overriding) the styling of the individual charts. In order to achieve the expected behavior, I redesigned the current available wrapper with interfaces and could not just further extend it. Additionally, FSharp.Plotly provides strongly typed style options to get rid of error prone string based styling.

For me it is a new experience to share an open source project within the awesome F# community.
I hope FSharp.Plotly turns out to be useful.

**Comment by kkkmail** [comment]
I looked at both XPlot and this library and choose this one primarily due to the usage of strong F# types to handle various options.

**Comment by kMutagene** [comment]
This issue is quite old and I think everything on the topic has been said back then. If a new discussion about comparison with XPlot is of interest, please submit a new issue

**Comment by bmitc** [comment]
Hello! I found this issue by searching the issues for "xplot". :)

I think it would be helpful to add a section to the README that explains not only that this is different from `XPlot.Plotly` but also maybe gives the reasons why this was created and points out key differences or improvements. I initially thought this was an evolution of that project, and then when I saw that wasn't the case, I asked myself what the difference was and why I should use one over the other.

I think that information would be very helpful to clear up any confusion between the two packages!

**Comment by kMutagene** [comment]
I am not sure why an explicit comparison with XPlot is needed, as it is clearly stated what the goal of this library is - providing a  .NET API for creating and rendering plotly charts. In that regard, it has far surpassed XPlot both in feature completeness and type safety, as is also stated in [XPlot's readme](https://github.com/fslaborg/XPlot#xplot).

**Comment by kMutagene** [comment]
It might however be beneficial to do an "upgrade from XPlot" section for the docs that ports some samples.

**Comment by bmitc** [comment]
> .NET API for creating and rendering plotly charts

That's exactly what `XPlot.Plotly` is, so why does that clarify anything?

> I am not sure why an explicit comparison with XPlot is needed

Isn't that clear from what I pointed out? It isn't necessarily about a direct comparison but simply providing a little bit of clarification of the history of the two projects and why Plotly.NET was created.

The originator of this issue, @tpetricek, is one of the OG F# evangelists, and I also pointed out why it's confusing, especially since Plotly.NET has changed names. It shouldn't be surprising that people might get confused between `XPlot.Plotly`, `FSharp.Plotly`, and `Plotly.NET` and wander what's the deal. I did.

I just think a small blurb in the README or a FAQ could go a long way in providing clarity, especially when it's a new project that is meant to replace an already existing project or library that basically does the same thing. The fact that XPlot put it in their README corroborates that.

It's just a suggestion. :)
