### ISSUE TITLE
Histogram with Orientation 'Horizontal' does not display data

### ISSUE THREAD

**Issue by dobretzberger** [plotly/Plotly.NET#256]
### Description

When Creating a Histogram with Horizontal Orientation, the resulting Chart is empty.
It is the same behaviour which can be seen in the docs on https://plotly.com/fsharp/histograms/ but it still exists in the latest preview.16

This is the code:

```fsharp
open Plotly.NET
let N = 500
let rnd = System.Random()
let x = Array.init N (fun _ -> rnd.NextDouble())
Chart.Histogram(
               x,
               Orientation=StyleParam.Orientation.Horizontal
               )  // issue with horizental allign
```

### Expected behavior

Should display a correct histogram with horizontal alignment

### Actual behavior

Displays no data in the chart.

### Related information 

* Windows 10
* Plotly.NET, 2.0.0-preview.16
* .net48, FSharp.Core 5.0.2

**Comment by kMutagene** [comment]
Thanks for reporting in, orientation not working is a bug, but it already has been fixed (but not released yet).

In short, the error is that the data has to be set for Y instead of X for data binned on the Y axis. You can use this workaround creating the trace manually in the meantime:

```fsharp
Trace2D.initHistogram(
    Trace2DStyle.Histogram(
        Y = [1;2;3;3;4;4;4;5;6;6;7]
    )
)
|> GenericChart.ofTraceObject true
|> Chart.show
```

![image](https://user-images.githubusercontent.com/21338071/149896514-65e46fad-e6f2-4ed9-a705-ee9acc85ffc1.png)
