### ISSUE TITLE
[Bug] Mathjax scripts get referenced multiple times, even in charts without Mathjax

### ISSUE THREAD

**Issue by bvenn** [plotly/Plotly.NET#259]
### Description

When working with MathTex text styling in charts the script tag is added multiple times within the html document. For every chart, another script set is added. Even if no MathTex is used, the scripts keep appearing. Even if appendTags is set to false they are added to chart3.

### Repro steps

```
#r "nuget: Plotly.NET, 2.0.0-preview.16"

open Plotly.NET

let chart1 = 
    Chart.Point([1,2])
    |> Chart.withXAxisStyle "$\lambda$" 
    |> Chart.withMathTex(true)
    |> Chart.show

let chart2 =  
    Chart.Point([1,2])
    |> Chart.withXAxisStyle "$\lambda$" 
    |> Chart.withMathTex(true)
    |> Chart.show

let chart3 =  
	Chart.Point([1,2]) |> Chart.show
```

The html of chart3 looks as follows:
![image](https://user-images.githubusercontent.com/28917670/150512308-b6fa4b95-860c-4c6c-b6f0-1e47cf5b4857.png)

### Expected behavior

Scripts are referenced only once and no script is referenced when no MathTex is activated.

**Comment by kMutagene** [comment]
This bug was caused by the way the global defaults are used on chart creation:

`GenericChart.ofTraceObject`, a function that gets used by every `Chart.XYZ` constructor, used the mutable global default values for things such as `DisplayOptions`. This caused functions that do not change the full object, but append values to it such as `Chart.WithMathTex` to mutate the global default display options instead of the display options used in the respective chart only.

My solution is to initialize charts with a copy of global default values in  `GenericChart.ofTraceObject` and `GenericChart.ofTraceObjects`
