### ISSUE TITLE
Chart.Grid() and Chart.SingleStack() mutate the input charts inplace

### ISSUE THREAD

**Issue by nhirschey** [plotly/Plotly.NET#271]
### Description

Chart.Grid() and Chart.SingleStack() mutate the input charts inplace. This means that if you want to present the same charts in different ways (like Chart.Grid() version and a Chart.combine version), Chart.combine will not work after you've run Chart.Grid() or Chart.SingleStack() on the input charts.

### Repro steps

Run these 3 chunks in sequence, the 3rd chunk produces the wrong chart.

```fsharp
#r "nuget: Plotly.NET,2.0.0-preview.18"
open Plotly.NET
let x = [("a",1);("b",2);("c",3)] |> Chart.Column
let y = [("a",2);("b",3);("c",4)] |> Chart.Column

// this correctly produces a combined chart
[x; y]
|> Chart.combine
|> Chart.show
```
![image](https://user-images.githubusercontent.com/5226115/158184261-d6200b54-4a6f-49c3-b85b-a101a6fe58b5.png)

```fsharp
// this correctly produces a grid chart
[x; y]
|> Chart.Grid(2,1)
|> Chart.show
```
![image](https://user-images.githubusercontent.com/5226115/158184506-9688bb7b-0a81-4e87-b048-2ea8a8935607.png)

```fsharp
// this does not work. It will again produce a grid chart
[x; y]
|> Chart.combine
|> Chart.show
```
![image](https://user-images.githubusercontent.com/5226115/158184622-7b4f52b1-22f8-45db-938b-0055a3fcd6c6.png)

### Related information 

* Operating system windows 11
* Branch preview.18
* .NET Runtime, CoreCLR or Mono Version: .net 6.0

**Comment by kMutagene** [comment]
This is (sadly) by design due to a whole lot of internals of the library. Actually, all styling functions mutate the input chart - combine only seems to work differently because it does not need to make changes in your case, while Chart.Grid actually changes things such as the axis anchor.

In general, i would recommend just creating two charts. If you want to have re-usable chart components, create them as return values of a function. I know this is not ideal, but it will stay like this for a time (see #254 for what a gigantic hassle it is to make charts immutable)

**Comment by nhirschey** [comment]
Thank you for that insight. It does look like a lot of work to make it immutable.

I'll follow your suggestions for creating re-usable chart components.
