### ISSUE TITLE
Plot with more than one Y using C#

### ISSUE THREAD

**Issue by mdmoura** [plotly/Plotly.NET#279]
Using C# I have the following:

    List<Int32> xValues = Enumerable.Range(1, 500);
    List<Single> y1Values = getY1Values();
    List<Single> y2Values = getY2Values();  

How to create one Plotly.Net C# chart with 2 lines (for y1Values and for y2Values)?

I was only able to create with one set of y values:

    GenericChart.GenericChart chart = Chart2D.Chart.Line<Int32, Single, String>(xValues, y1Values);

**Comment by kMutagene** [comment]
I cannot reproduce your exact example because i don't have the code for `getY1/2Values()`, but in general `Chart.Combine` (https://plotly.net/01_2_multiple-charts.html) is the top level API you are looking for. It creates a multichart from a collection of charts:

```csharp
using System;
using Plotly.NET;
using Microsoft.FSharp.Core; // use this for less verbose and more helpful intellisense
using Plotly.NET.LayoutObjects;

namespace Plotly.NET.Tests.CSharp
{
    class Program
    {
        static void Main(string[] args)
        {
            double[] x = new double[] { 1, 2 };
            double[] y1 = new double[] { 5, 10 };
            double[] y2 = new double[] { 10, 20 };

            GenericChart.GenericChart[] charts = {
                Chart2D.Chart.Line<double, double, String>(x, y1),
                Chart2D.Chart.Line<double, double, String>(x, y2)
            };

            Chart.Combine(charts)
                .Show();
        }
    }
}
```

![image](https://user-images.githubusercontent.com/21338071/165032180-8cd184cd-191e-4866-80ff-5777fa047aaf.png)
