### ISSUE TITLE
In Chart.withLegendStyle, StyleParam.XAnchorPosition does not seem to have an effect

### ISSUE THREAD

**Issue by nhirschey** [plotly/Plotly.NET#289]
### Description

When I try to orient a legend, `YAnchorPosition` works as I expect but `XAnchorPosition` does not seem to have an effect.

### Repro steps

```fsharp
#r "nuget: Plotly.NET"

open Plotly.NET

let xs = [1.0 .. 4]
let y1 = xs |> List.map (fun x -> x * 2.0)
let y2 = xs |> List.map (fun x -> x * 3.0)
```

These charts look the same to me:

```fsharp
// left
[Chart.Line (xs, y1); Chart.Line (xs, y2)]
|> Chart.combine
|> Chart.withTitle("Left")
|> Chart.withLegendStyle(Orientation=StyleParam.Orientation.Horizontal,
                         X=0,
                         XAnchor=StyleParam.XAnchorPosition.Left)
|> Chart.show

// right
[Chart.Line (xs, y1); Chart.Line (xs, y2)]
|> Chart.combine
|> Chart.withTitle("Right")
|> Chart.withLegendStyle(Orientation=StyleParam.Orientation.Horizontal,
                         X=0,
                         XAnchor=StyleParam.XAnchorPosition.Right)
|> Chart.show
```
![image](https://user-images.githubusercontent.com/5226115/169397933-fdc34d28-2a1a-42c9-be16-9899233f2c02.png)
![image](https://user-images.githubusercontent.com/5226115/169398127-ff939860-6571-443c-a4f2-988ee2e6f402.png)

### Expected behavior

I expect the left chart to be as it is but I expect the right chart's legend to be right-aligned at x=0.

### Actual behavior
the legend positions are the same.

### Related information 

* Operating system Windows 11
* .NET 6,

**Comment by kMutagene** [comment]
This seems to be intended. See the plotly.js [docs](https://plotly.com/javascript/reference/layout/#layout-legend-xanchor) : 

> Sets the legend's horizontal position anchor. This anchor binds the `x` position to the "left", "center" or "right" of the legend. Value "auto" anchors legends to the right for `x` values greater than or equal to 2/3, anchors legends to the left for `x` values less than or equal to 1/3 and anchors legends with respect to their center otherwise.

Seems like you have to controll the position additionally via increasing `X`: 

> Type: number between or equal to -2 and 3
Sets the x position (in normalized coordinates) of the legend. Defaults to "1.02" for vertical legends and defaults to "0" for horizontal legends.

so a combination of `X = 1` and `XAnchor = "right"` should work. 

```fsharp
[Chart.Line (xs, y1); Chart.Line (xs, y2)]
|> Chart.combine
|> Chart.withTitle("Left")
|> Chart.withLegendStyle(Orientation=StyleParam.Orientation.Horizontal,
                         X=1,
                         XAnchor=StyleParam.XAnchorPosition.Right)
|> Chart.show
```

However, this will lead to this result, because `XAnchor` falsely set the `YAnchor` attribute currently >.<

![image](https://user-images.githubusercontent.com/21338071/169815075-0d64371d-146c-44ac-b258-b3d2ef383933.png)

I patched this already and this will be live with the next release.

![image](https://user-images.githubusercontent.com/21338071/169815048-bcb8fc98-61be-4f1a-a6a8-ae4177ec2083.png)

**Comment by nhirschey** [comment]
That looks great, thank you! Good eye catching the typo causing the bug; that would be hard to catch.
