### ISSUE TITLE
Map Formatting 

### ISSUE THREAD

**Issue by shuganth** [plotly/Plotly.NET#349]
I am working on project to replicate an map of something similar, Can you please help to bring this map in exact format as in the below image.
![Picture1](https://user-images.githubusercontent.com/51713075/186146966-0afa3440-6c44-4df1-9dae-9cbe638f4dec.png)

**Comment by kMutagene** [comment]
I hope i understand you correctly that you are looking for inspiration on how to approach your project, because i will not implement your project for you. 

You also gave no context at all - what language are you using? where's your data coming from?

However, here are some pointers on how to create a map like this:

- look into [how to use GeoJson](https://plotly.net/05_2_choropleth-map.html#Using-GeoJSON) with Choropleth maps
- Add a PointGeo chart on top for the red points
- Use a fitting map scope and projection (above docs link should help here as well, the map there looks quite similar)

In general i would kindly ask to join the discord server for questions like this, and use issues for the purpose of tracking bugs and feature requests.

**Comment by shuganth** [comment]
Thanks for the reply. I am using C# to generate a map which show the density of the people. 
```
            IEnumerable<string[]>? lines = File.ReadAllLines(@"C:\Users\axxx\Downloads\2011_us_ag_exports.csv").Select(a => a.Split(','));
            IEnumerable<string[]>? lines2 = File.ReadAllLines(@"C:\Users\axxxxx\Downloads\fips.csv").Select(a => a.Split(','));
            List<string> Locationcode = new List<string>();
            List<string> totalexports = new List<string>();
            foreach (var lin in lines2)
            {
                Locationcode.Add(lin[0]);
                totalexports.Add(lin[1]);
            }

            var geoJson = JsonConvert.DeserializeObject(File.ReadAllText(@"C:\Users\axxx\Downloads\fips4.json"));/
            var maps2 = ChartMap.Chart.ChoroplethMap<string, string>(locations: list, z: list2, LocationMode: 
            StyleParam.LocationFormat.GeoJson_Id, GeoJson: geoJson, ShowLegend: true, UseDefaults: false);
            maps2.Show();
```

I am looking to use zip3 with with the layout of https://github.com/mathbiol/sparcs/blob/master/zip3.geojson or can we use the shp.file to change the map if so could you please help out to change the map layout.
