### ISSUE TITLE
Charts rendered in Jupyter notebooks

### ISSUE THREAD

**Issue by minibix** [plotly/Plotly.NET#36]
Love this library, however, is there any plan to implement a method which outputs chart HTML / CSS that can be represented immediately in Jupyter Lab / notebooks? I've not looked into what data format Jupyter requires to show charts, but I tested XPlot and the charts render immediately inside the notebook.

**Comment by muehlhaus** [comment]
Thank you for the feature request. I changed the HTML representation, that it should work using the developer branch... We will test the new version and release a nuget package by the end of next week. To show the inline chart you need to use |> Chart.toChartHTML and then use |> Display (using ifsharp) or |> HtmlString (using dotnet.interactive) instead of Chart.Show. Here is an example: https://github.com/ZimmerD/COVIS-19

**Comment by minibix** [comment]
Superb - will report back with any issues.

**Comment by kMutagene** [comment]
Additionally, [Plotly.NET.Interactive](https://www.nuget.org/packages/Plotly.NET.Interactive/) is now available via nuget if you are using dotnet interactive notebooks. just reference the package, and the formatter will automatically be registered:

![image](https://user-images.githubusercontent.com/21338071/101763025-7b41e980-3ade-11eb-9e7e-8034f20c8d41.png)
