### ISSUE TITLE
`#i` is not rendering in the documentation for notebooks

### ISSUE THREAD

**Issue by bmitc** [plotly/Plotly.NET#408]
On the [Plotly.NET](https://plotly.net/) homepage, in the ["For dotnet interactive notebooks"](https://plotly.net/#For-dotnet-interactive-notebooks) section, there is the note:

![image](https://github.com/plotly/Plotly.NET/assets/65685447/16436304-8ebb-461e-9f35-4e83f8187153)

However, there is no letter following the `#`, so I was confused how to run this. So I inspected the source of the documentation, expecting to find it was just a typo, but the source actually has `#i`.

https://github.com/plotly/Plotly.NET/blob/36a9c1280c69c70971ae030f26a93c75d4667a04/docs/index.fsx#L109-L112

So it seems like the `i` in `#i` is not rendering properly or is getting stripped out in the processing? I'm not entirely sure.

**Comment by kMutagene** [comment]
Weird. It seems like the `i` is actually stripped from the the text by the docs generation process. you can see that it is there in the source:
https://github.com/plotly/Plotly.NET/blob/36a9c1280c69c70971ae030f26a93c75d4667a04/docs/index.fsx#L110-L111
Might be fixable by moving it into a markdown section code block. I'll have a look. However, these days it is increasingly unlikely that the fix is still needed and I might just remove it completely

**Comment by bmitc** [comment]
Yea, I noticed it was in the source as well, so figured something was probably stripping it out, somewhere.

Sounds good removing it if not needed! Always nice when you can do that. 🙂 I've found a few other tiny things in the docs, but those are where I can just submit a PR with corrections (if I can remember what they were).

**Comment by kMutagene** [comment]
fixed ;) https://plotly.net/#For-dotnet-interactive-notebooks

**Comment by bmitc** [comment]
Nice! Thanks!
