### ISSUE TITLE
Chart descriptions do not work if Cytoscape.NET.Interactive is referenced simultaneously

### ISSUE THREAD

**Issue by bvenn** [plotly/Plotly.NET#425]
I have no clue if this belongs to Plotly.NET, Cytoscape.NET or both, but if you load both interactive references, ChartDescriptions do not work anymore.

```fsharp
#r "nuget: Plotly.NET, 4.2.0"
#r "nuget: Plotly.NET.Interactive, 4.2.1"
#r "nuget: Cytoscape.NET, 0.2.0"
#r "nuget: Cytoscape.NET.Interactive, 0.2.0"


open Plotly.NET
open Cytoscape.NET

Chart.Point([1,2])
|> Chart.withDescription [Giraffe.ViewEngine.HtmlElements.rawText "Hello"]
```

```
typecheck error This expression was expected to have type
'Giraffe.ViewEngine.HtmlElements.XmlNode (Giraffe.ViewEngine.StrongName, Version=2.0.0.0, Culture=neutral, PublicKeyToken=028aa8e2a326f4d0)'
but here has type
'Giraffe.ViewEngine.HtmlElements.XmlNode (Giraffe.ViewEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)'
```

For information, if you exclude the first Plotly.NET 4.2.0 reference, it works...

**Comment by Peter-B-** [comment]
Hi @bvenn,

I just copied your code into a new Polyglot Notebook and it works. Excluding the first line did not change anything.

**Comment by bvenn** [comment]
@Peter-B- I did the same and the first time it showed the same error. The second time after restarting the kernel it worked just fine. The same pattern occurred when I switched the references to Cytoscape beeing first. I spoke to @kMutagene on the conference and he already had an idea what happened.

@kMutagene feel free closing this issue if the issue just affects my local setup

**Comment by kMutagene** [comment]
I find it weird that it works for you @Peter-B-, because the error makes sense: Plotly.NET and Cytoscape.NET use different view engine packages ([Giraffe.ViewEngine.StrongName](https://www.nuget.org/packages/Giraffe.ViewEngine.StrongName/2.0.0-alpha1) vs [Giraffe.ViewEngine](https://www.nuget.org/packages/Giraffe.ViewEngine/)) (i have to fix this for Cytoscape.NET), because Plotly.NET needs to be signed ([long story](https://github.com/plotly/Plotly.NET/issues/175)). 

Cytoscape.NET only uses the engine internally, while Plotly.NET actually allows you to use the ViewEngine html dsl for chart description. It could be possible for type inference to know which assembly to use, but when one shadows the other as the functions are named exactly the same, i would expect this error to occur. So i would guess @bvenn if you reverse the dependencies (loading cytoscape first, then plotly) it should work

**Comment by kMutagene** [comment]
Closing this as there is not much we can do when libraries use incompatible transient dependencies.
