### ISSUE TITLE
Unable to change the legend font size when global font size is defined in layout

### ISSUE THREAD

**Issue by kunjiangkun** [plotly/Plotly.NET#440]
### Description
Not able to set legend font size in layout when global font size is defined.

### Repro steps

var plotLayout = Layout.init<bool>(                
    Legend: Legend.init(
        Font: Font.init(Size: 5),
        GroupTitleFont: Font.init(Size: 5),
        TraceGroupGap: 0, VerticalAlign: VerticalAlign.Middle, ItemSizing: TraceItemSizing.Trace
        ),
    Font: Font.init(Size: 10)
    );

plot.WithLayout(plotLayout);

### Expected behavior

Legend font size should be 5.

### Actual behavior

Legend font size is 10.

### Known workarounds

None.

### Related information 
,NET Framework 4.8.

**Comment by kMutagene** [comment]
Hi @kunjiangkun,

thanks for reporting this. This has already been fixed in https://github.com/plotly/Plotly.NET/commit/39dcefaada8fd244e5947ec1f24f8363e7a01515, but is not released yet. For a temporary workaround, you can set the `font` attribute via DynamicObj style:

```csharp
using Plotly.NET;
using Plotly.NET.LayoutObjects;

var legend = 
    Legend.init(
        GroupTitleFont: Font.init(Size: 5),
        TraceGroupGap: 0, 
        VerticalAlign: StyleParam.VerticalAlign.Middle, 
        ItemSizing: StyleParam.TraceItemSizing.Trace
    );

legend.SetValue("font", Font.init(Size: 5));

var plotLayout = Layout.init<string>(
    Legend: legend,
    Font: Font.init(Size: 10)
);

var plot = 
    Chart2D.Chart.Point<int, int, string>(
        x: new [] {1,2}, 
        y: new [] {1,2},
        ShowLegend: true
    );

plot.WithLayout(plotLayout)
```

![image](https://github.com/plotly/Plotly.NET/assets/21338071/ddfa5d4a-85c5-4c4f-8fdc-ad0e1dece376)
