### ISSUE TITLE
Legend option missing in Layout.init in release 5.0

### ISSUE THREAD

**Issue by kunjiangkun** [plotly/Plotly.NET#455]
### Description

What happened to Legend option in Layout.init in version 5.0? Is this a broken change? How should legend be set with Layout? WithLegend only turn legend on or off.

Version 5.0.0.

**Comment by kMutagene** [comment]
We now support multiple legends per layout, which is a recent plotly.js feature. Since setting legends now works similar to swtting axes, a single `Legend` option for creating Layouts does not make sense anymore.

There are however multiple methods in the `Layout` and `Chart` namespaces to handle the new logic, which is why this

> WithLegend only turn legend on or off.

Confuses me, do you have a minimal reproducible example for that?

**Comment by kMutagene** [comment]
Do you maybe set a custom plotly.js source? If that is the case, make sure to reference a version of plotly.js that supports multiple legends
