### ISSUE TITLE
'NaN' disturbs axis format

### ISSUE THREAD

**Issue by caroott** [plotly/Plotly.NET#46]
### Description

When i want to create Boxplots of float arrays and combine them, i run into an issue if one or more of the arrays consist of 'NaN'. With the NaNs in the array the axis seems to be treated as a category axis and not as a value axis, leading to a non-continuously labeled axis.

 
![image](https://user-images.githubusercontent.com/39764934/87065531-6c929600-c211-11ea-9bc2-655a8b69c5ea.png)

### Repro steps

1. Open a fsx file and load FShar.Plotly

2. Run the following snippet:
```
let testArr =
    [|
        (1, [|nan;nan;nan|]);
        (2, [|0.07427533383; 0.757004965; 0.6258709596|]);
        (3, [|0.2661355688; 0.7138485368; 0.3500703892|])
    |]

testArr
|> Array.map (fun (number, values) ->
    Chart.BoxPlot ("y",values, Name=(sprintf "N: %i" number),Boxpoints=StyleParam.Boxpoints.All,Orientation=StyleParam.Orientation.Vertical)
)
|> Chart.Combine
|> Chart.withMargin (Margin.init(Left=200.))
|> Chart.Show
```

### Known workarounds

Filter all arrays and remove every NaN present

**Comment by kMutagene** [comment]
I think your workaround should be the preferred way to circumvent this issue, as trying to plot nan values in distribution does not seem to make too much sense for me, so i think we should expect the user to filter the input properly instead of botching up a prefilter that can break other applications.
