### ISSUE TITLE
Support DateTimeOffset type

### ISSUE THREAD

**Issue by drhumlen** [plotly/Plotly.NET#69]
### Description

We use DateTimeOffset for everything instead of regular DateTime since it maintains time zone information. Right now we have to  `|> List.map (fun datetimeoffset -> datetimeoffset.UtcDateTime)` every time we chart up something. 

Would it be possible to support DateTimeOffset directly?

**Comment by kMutagene** [comment]
Hi @drhumlen,

The problem here is `DateTimeOffset` not implementing `IConvertible` while `DateTime` does. For me it seems like we would not really have much of a choice here other than implementing overloads for every single chart function on `DateTimeOffset` for that to work, which seems quite overkill for a use case that can be solved with a single mapping/conversion step. Implementing `IConvertible` for `DateTimeOffset` also [seems to be not that trivial](https://stackoverflow.com/questions/11726502/implementing-iconvertible-like-functionality-for-non-modifiable-types) and might also be overkill on your side, so i am afraid I do not have any good idea to tackle this from our side atm. There might be a solution coming up though, depending on when and if erased union types become a thing in F#.

**Comment by drhumlen** [comment]
Aha. That makes sense. Yeah implementing overloads for every method seems like tedious work when everything else works fine with just `IConvertible`. I guess the best workaround for now is for us to make some helpers that converts a list of DateTimeOffset to DateTime.

**Comment by kMutagene** [comment]
Cloosing for now, might be revisited when erased unions are a thing in F# so we could use things like `(IConvertible|DateTimeOffset|SomeOtherType)` as input
