### ISSUE TITLE
latex issure

### ISSUE THREAD

**Issue by wang-jinbo** [plotly/Plotly.NET#72]
version:2.0.0-beta8
```F#
let header = [ "$x_0$"; "迭代次数"; "数值结果"; "数值误差" ]
```
The thing is that I can't produce ```LaTeX``` output out of line, which can be produced under ```Plotly``` on ```python```, ```MATLAB```

**Comment by kMutagene** [comment]
Hi @Wongboo 

I would really appreciate a full code example, but i managed latex output to work in principle.

The problem is MathJax (the tex rendering engine used in plotly tex examples) not being referenced in our HTML scaffold. For a workaround until this is properly implemented, add these script tags to the html:

```html
<script type="text/x-mathjax-config;executed=true">MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']], processEscapes: true}});</script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML%2CSafe.js&ver=4.1"></script>
```

Additionally, as tex uses a lot of `\` characters, your tex strings should be escaped using `@`:

```fsharp
[
    Chart.Line([(1.,2.)],@"$\beta_{1c} = 25 \pm 11 \text{ km s}^{-1}$")
    Chart.Line([(1.,2.)],@"$\beta_{1c} = 25 \pm 11 \text{ km s}^{-1}$")
]
|> Chart.Combine
|> Chart.Show
```

Which will then look like this:

![image](https://user-images.githubusercontent.com/21338071/114561783-2b328980-9c6e-11eb-8b5d-d07af074bb75.png)

From our side it is most likely the best to set this on the `Config` level of `GenericChart`, providing a `Chart.withMathTex` function indicating that the mathtex script should be contained in the html scaffold.

**Comment by wang-jinbo** [comment]
@kMutagene 
I kind of understand, so this generally means that until the official support is established, We have to change the source code of ```Plotly.NET``` or manually add 
```
<script type="text/x-mathjax-config;executed=true">MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']], processEscapes: true}});</script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML%2CSafe.js&ver=4.1"></script>
```
to the chart which might be too complicated since no ```API``` in ```GenericChart``` supports directly adding these script tags. Am I right?

**Comment by kMutagene** [comment]
> or manually add [script tags]
to the chart which might be too complicated since no ```API``` in ```GenericChart``` supports directly adding these script tags. Am I right?

I can think of two workarounds that might work for you in the meantime:

- The output of `Chart.Show` is a html text file like any other, so you can open the files programmatically and add those lines. 

- The `GenericChart.toChartHTML` returns the contents of that file as a string, so you can add these lines there and then write the content to a file like this:

	```fsharp
	[
    Chart.Line([(1.,2.)],@"$\beta_{1c} = 25 \pm 11 \text{ km s}^{-1}$")
    Chart.Line([(1.,2.)],@"$\beta_{1c} = 25 \pm 11 \text{ km s}^{-1}$")
    ]
	|> Chart.Combine
	|> Chart.toChartHTML
    |> `add the missing lines`
	|> `write to a .html file`
	```

**Comment by wang-jinbo** [comment]
So temporarily solution is to change the HTML directly through adding these lines.
In the long term, wait for the ```API``` change in ```MathJAX```.
Thanks for your help!

**Comment by kMutagene** [comment]
Exactly, i don't imagine this feature taking too long to implement though

**Comment by kMutagene** [comment]
@Wongboo Watch out for the next release, you will be able to use `Chart.WithMathTex`:


```fsharp
[
    Chart.Line([(1.,2.)],@"$\beta_{1c} = 25 \pm 11 \text{ km s}^{-1}$")
    Chart.Line([(1.,2.)],@"$\beta_{1c} = 25 \pm 11 \text{ km s}^{-1}$")
]
|> Chart.Combine
|> Chart.withTitle @"$\beta_{1c} = 25 \pm 11 \text{ km s}^{-1}$"
|> Chart.WithMathTex(true)
```

![image](https://user-images.githubusercontent.com/21338071/114695429-e7965900-9d1b-11eb-914a-fbca21b03746.png)
